name: Create Release
run-name: ${{ github.actor }} is creating a release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    # - name: Run tests
    #   run: cargo test --verbose

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with: 
        name: sub-store
        path: /home/runner/work/SubStore/SubStore

  Create-Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve release assets
        uses: actions/download-artifact@v4
        with:
          name: sub-store
          path: /home/runner/work/SubStore/SubStore

      - name: Check Output
        run: ls -alh ./target/release

      - name: Zip up release
        run: zip release.zip /home/runner/work/SubStore/SubStore 


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: todo
          draft: false
          prerelease: false

      - name: Upload release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip

